# I need to refer nodejs tasks in common folder
# mysql is one role
# common is also another role
# I need to import a task nodejs.yaml in catalogue

- name: Disable current MySql version
  ansible.builtin.command: yum module disable mysql -y

- name: copy Mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySql community version
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: restart and enable MySql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: setup mysql root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1